language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - sed -i 's/--no-build-vignettes\ --no-manual\ *//' ./travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo apt-get install texinfo texlive-latex-base texlive-fonts-extra texlive-fonts-recommended texlive-latex-recommended

install:
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
  - WARNINGS_ARE_ERRORS=1

notifications:
  email:
    on_success: change
    on_failure: change
