# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Return Triangular Numbers
#' @description
#' Return the series of triangular (/triangle) numbers up to a number of
#' \code{n} rows of a triangle. The series has the entry number "A000217"
#' at \url{https://oeis.org/} and starts like this: 0, 1, 3, 6, 10, ...
#' @param n Positive integer value for number of triangle rows.
#' @return
#' Returns an integer vector of length \code{n}.
#' @name ntri
#' @keywords triangle triangular number
#' @import Rcpp
#' @author Sven E. Templer (\email{sven.templer@@gmail.com})
NULL

#' @export ntri
ntri <- function(n) {
    .Call('miscset_ntri', PACKAGE = 'miscset', n)
}

#' Return Sorted Table
#' 
#' R/C++ version of \code{sort(table(x))}, with the option to switch between
#' increasing or decreasing order and to include counts of \code{NA}.
#' 
#' @param x Vector to create table of counts
#' @param decr Decreased order if \code{TRUE}.
#' @param na Include \code{NA} if \code{TRUE}.
#' @return
#' Named integer Vector \code{n}.
#' @name sortable
#' @keywords table sort
#' @import Rcpp
#' @author Sven E. Templer (\email{sven.templer@@gmail.com})
NULL

#' @export sortable
sortable <- function(x, decr = TRUE, na = TRUE) {
    .Call('miscset_sortable', PACKAGE = 'miscset', x, decr, na)
}

